"""add financial fields to orders

Revision ID: 776312ce7fda
Revises: 7d4cd9156c46
Create Date: 2026-05-06 13:10:42.732701+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776312ce7fda'
down_revision: Union[str, None] = '7d4cd9156c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('shipping_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_amount')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
