"""add review_count to products

Revision ID: ab8058a27ce3
Revises: fa2c827aa4c3
Create Date: 2026-05-11 21:11:20.433518
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab8058a27ce3'
down_revision: Union[str, None] = 'fa2c827aa4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('prep_time', sa.String(length=50), nullable=True),
    sa.Column('cook_time', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.alter_column('products', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='[]',
               existing_nullable=True)
    op.drop_column('products', 'brand')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'difficulty')
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('zip', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zip')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'full_name')
    op.add_column('products', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('products', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    # ### end Alembic commands ###
